# Generated by Django 2.2.4 on 2020-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=100)),
                ('server_count', models.IntegerField(default=0)),
            ],
        ),
    ]
