# Generated by Django 2.2.1 on 2019-07-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
